### ISSUE TITLE
Readme update: mainClassName not set in newer gradle versions

### ISSUE THREAD

**Issue by nimloth05** [mini2Dx/parcl#11]
Accodring to this link: https://discuss.gradle.org/t/programmatically-set-applications-global-mainclassname-in-custom-plugin/22805 the application plugin uses an old api. I had to use 

    project.getConvention().getPlugin(ApplicationPluginConvention.class).setMainClassName("full.ClassName")

in my Gradle 4.4 project, to set the mainClassName variable. I think it would be nice if this would be mentioned in the Readme under a note section or something.

**Comment by tomcashman** [comment]
Thanks for reporting. I'm currentling using Gradle 4.8 without issue. However I have added a note to the README now in case other people encounter this issue.
