### ISSUE TITLE
Could you mention in the readme whether this produces .dmg, .deb, etc bundles?

### ISSUE THREAD

**Issue by hepcat72** [mini2Dx/parcl#8]
I want to be able to distribute my java app on Linux, Windows, and Mac using their typical packaging.  I can't tell from the readme whether this plugin creates .exe/.app/etc or whether it creates .dmg/.deb/etc.

**Comment by tomcashman** [comment]
I've updated the README with this info. The plugin currently generates the following platform natives:
 * Windows - .exe
 * Mac OS X - .app
 * Linux - .sh
 
I've added the following issues to add support for .deb and .rpm:
 * [#9 Generate .deb for Debian platforms](https://github.com/mini2Dx/parcl/issues/9)
 * [#10 Generate .rpm for Redhat platforms](https://github.com/mini2Dx/parcl/issues/10)
